version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: fe/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: be/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - FLASK_RUN_HOST=0.0.0.0
